.TH lxqt-leave 1 "January 2025" "LXQt 2.1." "LXQt Session Module"
.SH NAME
\fBlxqt-leave\fR \- Dialog to select logout, reboot, shutdown,
suspend, hibernate, and lock screen
.SH SYNOPSIS
\fBlxqt-leave\fR [\fIargument\fR]

.SH DESCRIPTION
\fBlxqt-leave\fR is a graphical Qt tool for easily triggering leave session
actions: logout, reboot, shutdown, hibernate, and lock screen. If run with
an argument, the dialog is not shown and the action is executed directly, unless "Ask for
confirmation" is checked in \fBlxqt-config-session\fR.
.SH OPTIONS
.PP
Available options:
.PP
\fB\-\-logout\fR
.RE
.PP
\fB\-\-lockscreen\fR
.RE
.PP
\fB\-\-suspend\fR
.RE
.PP
\fB\-\-hibernate\fR
.RE
.PP
\fB\-\-shutdown\fR
.RE
.PP
\fB\-\-reboot\fR
.RE
.PP
\fB\-\-help\fR
.PP
\fB\-\-version\fR
.RE
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxqt/lxqt-session/issues
.SH "SEE ALSO"
.\" any module must refer to the session application, for module overview and initiation
\fBstartlxqt.1\fR  LXQt session initialization and launch script (e.g. in \fB.xinitrc\fR)
.P
\fBlxqt-session.1\fR  LXQt \fIoverview\fR and complete session environment
.P
\fBlxqt-wayland-session.1\fR  LXQt Wayland session
.P
\fBlxqt-config-session.1\fR  LXQt session configuration
.P
\fBlxqt-config.1\fR  LXQt Configuration Center

