.TH lxqt-leave 1 "" "" "LXQt\ Helper"
.SH NAME
\fBlxqt-leave\fR \- easily logout, reboot, shutdown, suspend, hibernate and lock screen from a dialog
.SH SYNOPSIS
\fBlxqt-leave\fR [\fIargument\fR]
.SH DESCRIPTION
\fBlxqt-leave\fR is a graphical Qt tool for easily triggering leave session actions: logout, reboot, shutdown, hibernate and lock screen. If run with an argument, the dialog is not shown and the action is executed directly.
.SH OPTIONS
.PP
The options which apply to the \fBlxqt-leave\fR command are:
.PP
\fB\-\-logout\fR
.RE
.PP
\fB\-\-lockscreen\fR
.RE
.PP
\fB\-\-suspend\fR
.RE
.PP
\fB\-\-hibernate\fR
.RE
.PP
\fB\-\-shutdown\fR
.RE
.PP
\fB\-\-reboot\fR
.RE
.PP
\fB\-\-help\fR
.RE
.SH "REPORTING BUGS"
Report bugs to https://github.com/lxde/lxqt/issues
.SH AUTHOR
This manual page was created by \fBPaulo Lieuthier\fR \fI<paulolieuthier@gmail.com>\fR for the \fBLXQt\fR project.
